.\" $OpenBSD$
.\"
.\" Copyright (c) 2020 Jan Klemkow <j.klemkow@wemelug.de>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: October 2 2020 $
.Dt RP 4
.Os
.Sh NAME
.Nm rp
.Nd Comtrol RocketPort intelligent serial port cards device
.Sh SYNOPSIS
.Cd "rp* at pci?"
.Sh DESCRIPTION
This driver provides an interface to RocketPort multiport serial boards.
.Pp
The device minor numbers for this driver are encoded as follows:
.Bd -literal
    d c c u u u u u	- bits in the minor device number

    bits    meaning
    ----    -------
    uuuuu   physical serial line (i.e., unit) to use
            0-7 on a 8Y, 0-15 on a 16Y

    cc      card number

    d       dial-out flag
.Ed
.Sh SEE ALSO
.Xr com 4 ,
.Xr cy 4 ,
.Xr intro 4 ,
.Xr pci 4 ,
.Xr termios 4 ,
.Xr tty 4
.Sh AUTHORS
This driver was written under contract for Comtrol Corporation by
.An Theodore Ts'o Aq Mt tytso@mit.edu .
It was ported to
.Ox
by
.An Jan Klemkow Aq Mt j.klemkow@wemelug.de .
.Sh BUGS
Modem control does not work properly.
